version: "3.1"

# Language configuration
language: en

# NLU pipeline configuration (How the assistant understands the user's input)
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
  intent_classification: true
  entity_recognition: true
  user_features:
  - intent
  - entities
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1


# Policies configuration (How the assistant decides what actions to take based on user input and conversation history)
# Configuration for Rasa Core policies
policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_intents: true
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
  user_features:
  - intent
  - entities
  fallback_action_name: "action_repeat_message"  # Action when fallback occurs
assistant_id: 20241207-132732-medium-flush
